version: '3.4'
services:
  server:
    image: python:3.8-alpine
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    tmpfs:
        /tmp
  redis:
    image:
      redis:6-alpine

volumes:
  db-data:
